//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Lakasok
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RealEstateEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RealEstateEntities object using the connection string found in the 'RealEstateEntities' section of the application configuration file.
        /// </summary>
        public RealEstateEntities() : base("name=RealEstateEntities", "RealEstateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RealEstateEntities object.
        /// </summary>
        public RealEstateEntities(string connectionString) : base(connectionString, "RealEstateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RealEstateEntities object.
        /// </summary>
        public RealEstateEntities(EntityConnection connection) : base(connection, "RealEstateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Flat> Flat
        {
            get
            {
                if ((_Flat == null))
                {
                    _Flat = base.CreateObjectSet<Flat>("Flat");
                }
                return _Flat;
            }
        }
        private ObjectSet<Flat> _Flat;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Flat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlat(Flat flat)
        {
            base.AddObject("Flat", flat);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RealEstateModel", Name="Flat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Flat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Flat object.
        /// </summary>
        /// <param name="flatSK">Initial value of the FlatSK property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="vendor">Initial value of the Vendor property.</param>
        /// <param name="side">Initial value of the Side property.</param>
        /// <param name="district">Initial value of the District property.</param>
        /// <param name="elevator">Initial value of the Elevator property.</param>
        /// <param name="numberOfRooms">Initial value of the NumberOfRooms property.</param>
        /// <param name="floorArea">Initial value of the FloorArea property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static Flat CreateFlat(global::System.Int32 flatSK, global::System.String code, global::System.String vendor, global::System.String side, global::System.Byte district, global::System.Boolean elevator, global::System.Decimal numberOfRooms, global::System.Int16 floorArea, global::System.Decimal price)
        {
            Flat flat = new Flat();
            flat.FlatSK = flatSK;
            flat.Code = code;
            flat.Vendor = vendor;
            flat.Side = side;
            flat.District = district;
            flat.Elevator = elevator;
            flat.NumberOfRooms = numberOfRooms;
            flat.FloorArea = floorArea;
            flat.Price = price;
            return flat;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FlatSK
        {
            get
            {
                return _FlatSK;
            }
            set
            {
                if (_FlatSK != value)
                {
                    OnFlatSKChanging(value);
                    ReportPropertyChanging("FlatSK");
                    _FlatSK = StructuralObject.SetValidValue(value, "FlatSK");
                    ReportPropertyChanged("FlatSK");
                    OnFlatSKChanged();
                }
            }
        }
        private global::System.Int32 _FlatSK;
        partial void OnFlatSKChanging(global::System.Int32 value);
        partial void OnFlatSKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value, false, "Vendor");
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private global::System.String _Vendor;
        partial void OnVendorChanging(global::System.String value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Side
        {
            get
            {
                return _Side;
            }
            set
            {
                OnSideChanging(value);
                ReportPropertyChanging("Side");
                _Side = StructuralObject.SetValidValue(value, false, "Side");
                ReportPropertyChanged("Side");
                OnSideChanged();
            }
        }
        private global::System.String _Side;
        partial void OnSideChanging(global::System.String value);
        partial void OnSideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte District
        {
            get
            {
                return _District;
            }
            set
            {
                OnDistrictChanging(value);
                ReportPropertyChanging("District");
                _District = StructuralObject.SetValidValue(value, "District");
                ReportPropertyChanged("District");
                OnDistrictChanged();
            }
        }
        private global::System.Byte _District;
        partial void OnDistrictChanging(global::System.Byte value);
        partial void OnDistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Elevator
        {
            get
            {
                return _Elevator;
            }
            set
            {
                OnElevatorChanging(value);
                ReportPropertyChanging("Elevator");
                _Elevator = StructuralObject.SetValidValue(value, "Elevator");
                ReportPropertyChanged("Elevator");
                OnElevatorChanged();
            }
        }
        private global::System.Boolean _Elevator;
        partial void OnElevatorChanging(global::System.Boolean value);
        partial void OnElevatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NumberOfRooms
        {
            get
            {
                return _NumberOfRooms;
            }
            set
            {
                OnNumberOfRoomsChanging(value);
                ReportPropertyChanging("NumberOfRooms");
                _NumberOfRooms = StructuralObject.SetValidValue(value, "NumberOfRooms");
                ReportPropertyChanged("NumberOfRooms");
                OnNumberOfRoomsChanged();
            }
        }
        private global::System.Decimal _NumberOfRooms;
        partial void OnNumberOfRoomsChanging(global::System.Decimal value);
        partial void OnNumberOfRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 FloorArea
        {
            get
            {
                return _FloorArea;
            }
            set
            {
                OnFloorAreaChanging(value);
                ReportPropertyChanging("FloorArea");
                _FloorArea = StructuralObject.SetValidValue(value, "FloorArea");
                ReportPropertyChanged("FloorArea");
                OnFloorAreaChanged();
            }
        }
        private global::System.Int16 _FloorArea;
        partial void OnFloorAreaChanging(global::System.Int16 value);
        partial void OnFloorAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    }

    #endregion

}
